name: Publish docker images on docker hub
run-name: Publishing docker images
on:
  # release:
  #   types: [published]
  push
jobs:
  Build-and-publish-for-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Publish docker image
        uses: ./.github/actions/publish
        with:
          arch: amd64
          docker_user:  ${{ secrets.DOCKER_USER }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          tag: latest
